### PR TITLE
Update kodimote_sv.ts

### PR DESCRIPTION
**Pull request by eson57**
Hi,
Here's a Swedish update if you want it. 
I know I ones pushed an update for the original kodimote but it somehow never was implemented, and I can't find it any more.

### CODE REVIEW

**Comment by a-dekker** [comment]
I do know that there is a transifex page, but I cannot access that data.

**Comment by eson57** [comment]
It's okay. I'll use your fork if I'll ever get that damn tablet.  ;)

**Comment by a-dekker** [comment]
Why would that depend on the tablet?

**Comment by a-dekker** [comment]
@eson57 : 
The translations are a bit of a mess, it was on my todo list, but now I am forced to have a look at it ;-)

First the translations are not just for for Sailfish. but also for Ubuntu and Plasma. You can ignore the last two if you want. And besides that, the app and files where renamed from xbmcremote to kodimote. Most of Swedish is translated not, but not all. Could you have another look at the latest commit it before I make a new release on OpenRepos?

**Comment by a-dekker** [comment]
Oops, there are some missing files to be translated at the moment, I can reactivate them later, should be no problem if they are translated earlier.

**Comment by eson57** [comment]
Ok, doing it right now.

**Pull request merged**
