### PR TITLE
Makes the playback controls fit the tablet screen

### PR DESCRIPTION
**Pull request by dikonov**
Tested on Inoi T8 (1920x1200).

### CODE REVIEW

**Comment by a-dekker** [comment]
This pull request closed because it has issues?
The reason of the wrong size is related to the fact that it identifies as a "large screen", which I wrongly assume as always having the official jolla tablet resolution. I was planning to have al look at it, but if you can make a proper fix that would be nice.

**Comment by dikonov** [comment]
No. It simply was a duplicate of the second one.
 
Meanwhile, I tried to make the app show an icon of a folder for filesystem folders, but I cannot find the way to do it.
 
BTW What type is «thumbnail» in BrowserPage.qml?  Is is a string with some id|path of actual image data| or some structure from kodi?
  
>Суббота, 21 марта 2020, 22:06 +03:00 от a-dekker <notifications@github.com>:
> 
> 
>This pull request closed because it has issues?
>The reason of the wrong size is related to the fact that it identifies as a "large screen", which I wrongly assume as always having the official jolla tablet resolution. I was planning to have al look at it, but if you can make a proper fix that would be nice.
>—
>You are receiving this because you modified the open/close state.
>Reply to this email directly,  view it on GitHub , or  unsubscribe . 
 
 
--
Vyacheslav Dikonov

**Comment by a-dekker** [comment]
The other pull request was about the stop icon, this one was about the playback control scale. So what do you mean by duplicate?

**Comment by a-dekker** [comment]
Thumbnail is a custom type, defined in the components folder. The thumbnail itself should be a URI to the kodi server where the thumbnails are presented for client apps.

**Comment by dikonov** [comment]
> The other pull request was about the stop icon, this one was about the playback control scale. So what do you mean by duplicate?

The second pull request contains two commits. 1) replace 200 with 160 to change scale. 2) replace the lowres icon. The first request only suggests 1.

**Comment by dikonov** [comment]
> Thumbnail is a custom type, defined in the components folder. The thumbnail itself should be a URI to the kodi server where the thumbnails are presented for client apps.

I want to replace that URI with an URI pointing to a local icon of a folder IF the browser list item is a folder in Kodi and does not have associated image (instead of rectangles filled with repeating item title text), Later I would also add similar fallback icons for sound and video items.

**Comment by a-dekker** [comment]
> > The other pull request was about the stop icon, this one was about the playback control scale. So what do you mean by duplicate?
> 
> The second pull request contains two commits. 1) replace 200 with 160 to change scale. 2) replace the lowres icon. The first request only suggests 1.

pr #16 contains two icons.
this pr (#15) contains the qml code changed but has been close by you later.

So I am still a bit confused. Do you mean the qml change was just a suggestion not to be literally  implemented?

**Comment by dikonov** [comment]
> > > The other pull request was about the stop icon, this one was about the playback control scale. So what do you mean by duplicate?
> > 
> > 
> > The second pull request contains two commits. 1) replace 200 with 160 to change scale. 2) replace the lowres icon. The first request only suggests 1.
> 
> pr #16 contains two icons.
> this pr (#15) contains the qml code changed but has been close by you later.
> 
> So I am still a bit confused. Do you mean the qml change was just a suggestion not to be literally implemented?

I somehow screwed the pull requests than. There are two proposed changes: one is the replace 

```
-    property int iconResize: appWindow.largeScreen ? 200 : appWindow.mediumScreen ? 128 : appWindow.smallScreen ? 100 : 75
+    property int iconResize: appWindow.largeScreen ? 160 : appWindow.mediumScreen ? 128 : appWindow.smallScreen ? 100 : 75

```

The other is to replace the older smaller icon-m-stop.png with the new hires version.

**Comment by a-dekker** [comment]
This changes leads to a smaller playback control on the jolla tablet, but it is still acceptable imho.

**Pull request closed without merging**
